### Tworzenie nowego elementu
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "test 2 Aga Wera and Hania meeting",
  "subtitle": "together time",
  "type": "PlenarySession",
  "dateTimeStart": "2024-09-12T20:00:00.000",
  "dateTimeEnd":  "2024-09-12T24:00:00.000",
  "description": "drink",
  "building": "22",
  "room": "Hotel room",
  "reportsId": [

  ]
}


### Pobieranie wszystkich eventów
GET http://localhost:8080/api/events

### Pobieranie eventu po id
GET http://localhost:8080/api/events/af915a56-1ac9-4250-99b0-07f022c9a4cb

### Usuwanie eventu po id
DELETE http://localhost:8080/api/events/bff78941-2e84-4fac-9560-6be035d768d5

###Edycja eventu
PUT http://localhost:8080/api/events/09e64104-e04f-4378-9c8f-ef9ed808ee9a
Content-Type: application/json

{
  "title": "Nowy tytuł",
  "subtitle": "Nowy podtytuł",
  "type": "Other",
  "dateTimeStart": "2025-05-11T13:00:00.000",
  "dateTimeEnd": "2025-05-11T14:00:00.000",
  "description": "Zaktualizowany opis",
  "building": "Nowy budynek",
  "room": "Sala 101",
  "reportsId": []
}


### Pobieranie wszystkich raportów
GET http://localhost:8080/api/reports

### Pobieranie raportu po id
GET http://localhost:8080/api/reports/bc09b942-2cbf-4d59-a2fe-4f3d5a647400

### Stworzenie raportu
POST http://localhost:8080/api/reports
Content-Type: application/json

{
  "title": "TEST",
  "author": "John Doe",
  "description": "This report discusses the impact of AI on the healthcare industry.",
  "pdfURL": "http://example.com/reports/ai-in-medicine.pdf",
  "keywords": ["AI", "Healthcare", "Medicine", "TEST"]
}

### Stworzenie raportu
POST http://localhost:8080/api/reports
Content-Type: application/json

{
  "title": "3",
  "author": "2",
  "description": "2",
  "pdfURL": "2",
  "keywords": ["AI", "Healthcare", "Medicine", "TEST"]
}

### Stworzenie raportu
POST http://localhost:8080/api/reports
Content-Type: application/json

{
  "title": "Tytuł raportu",
  "author": "Autor",
  "description": "Opis raportu",
  "pdfURL": "http://example.com/report.pdf",
  "keywords": ["kluczowe", "słowa"],
  "eventId": "7e38f164-bac6-485d-a78e-4ba4d6165216"
}


### Usuwanie raportu po id
DELETE http://localhost:8080/api/reports/bc09b942-2cbf-4d59-a2fe-4f3d5a647400

###
POST http://localhost:30703/Dodaj/Hello/World
