### Tworzenie nowego eventu
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Test title",
  "subtitle": "test",
  "type": "PlenarySession",
  "dateTimeStart": "2024-09-12T20:00:00.000",
  "dateTimeEnd":  "2024-09-12T24:00:00.000",
  "description": "drink",
  "building": "22",
  "room": "Hotel room",
  "reportsId": [
  ]
}

### Pobieranie wszystkich eventów
GET http://localhost:8080/api/events

### Pobieranie eventu po id
GET http://localhost:8080/api/events/af915a56-1ac9-4250-99b0-07f022c9a4cb

### Usuwanie eventu po id
DELETE http://localhost:8080/api/events/bff78941-2e84-4fac-9560-6be035d768d5

###Edycja eventu
PUT http://localhost:8080/api/events/09e64104-e04f-4378-9c8f-ef9ed808ee9a
Content-Type: application/json

{
  "title": "Nowy tytuł",
  "subtitle": "Nowy podtytuł",
  "type": "Other",
  "dateTimeStart": "2025-05-11T13:00:00.000",
  "dateTimeEnd": "2025-05-11T14:00:00.000",
  "description": "Zaktualizowany opis",
  "building": "Nowy budynek",
  "room": "Sala 101",
  "reportsId": []
}

### Pobieranie wszystkich raportów
GET http://localhost:8080/api/reports

### Stworzenie raportu
POST http://localhost:8080/api/reports
Content-Type: application/json

{
  "title": "TEST",
  "authors": ["Jan Kowalski", "Anna Nowak"],
  "description": "This report discusses the impact of AI on the healthcare industry.",
  "pdfURL": "http://example.com/reports/ai-in-medicine.pdf",
  "keywords": ["AI", "Healthcare", "Medicine", "TEST"]
}

### Pobieranie raportu po id
GET http://localhost:8080/api/reports/bc09b942-2cbf-4d59-a2fe-4f3d5a647400


###Edycja raportu
PUT http://localhost:8080/api/reports/adf6374a-ee74-426e-8f5e-47474ba83bab
Content-Type: application/json

{
  "title": "3",
  "author": "2",
  "description": "2",
  "pdfURL": "2",
  "keywords": ["AI", "Healthcare", "Medicine", "TEST"]
}

### Usuwanie raportu po id
DELETE http://localhost:8080/api/reports/bc09b942-2cbf-4d59-a2fe-4f3d5a647400

### Logowanie
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}